### ISSUE TITLE
Get <TResult> from DialogWindow

### ISSUE THREAD

**Issue by WizMe-M** [mysteryx93/HanumanInstitute.MvvmDialogs#1]
Hi, trying your library in my project.
I'm stuck on trying to get some result from modal window. What if i wanna input some data in modal window and return this input back to the owner viewmodel? How could this be done?
Thanks in advance

```
var vm = _dialogService.CreateViewModel<InputModalViewModel>();
var input = await _dialogService.ShowDialogAsync(this, vm);
```

**Comment by mysteryx93** [comment]
Add a property to your ViewModel.

You got 'vm', carry any data you want in it. Both for input and output.

For convenience, you can create an extension method that shows the dialog and returns the value, as explained in the doc.

**Comment by WizMe-M** [comment]
Ah, gotcha. Thank you for your help
