### ISSUE TITLE
Broken with DialogHost and Avalonia 11.0.0-preview8

### ISSUE THREAD

**Issue by montex12** [mysteryx93/HanumanInstitute.MvvmDialogs#10]
Hello,

I am trying to run **Demo.Avalonia.DialogHost** sample with Avalonia 11.0.0-preview8.

I get an exception when running with the debugger.

`System.TypeInitializationException: The type initializer for DialogHostAvalonia.DialogOverlayPopupHost threw an exception.`
`MissingMethodException: Method not found: Avalonia.StyledProperty1<!!1> Avalonia.AvaloniaProperty.Register(System.String, !!1, Boolean, Avalonia.Data.BindingMode, System.Func2<!!1,Boolean>, System.Func3<Avalonia.AvaloniaObject,!!1,!!1>, System.Action2<Avalonia.AvaloniaObject,Boolean>)'.
`
The exception is thrown at:
`<StyleInclude Source="avares://DialogHost.Avalonia/Styles.xaml"/>`

Is there something wrong I am doing?
Is possible to make HanumanInstitute.MvvmDialogs.Avalonia+DialogHost compatible with preview8?

Thanks

**Comment by mysteryx93** [comment]
Would probably just need to recompile MvvmDialogs with newest preview

**Comment by mysteryx93** [comment]
Published an update
