### ISSUE TITLE
InitialFile in ShowSaveFileDialog

### ISSUE THREAD

**Issue by Tanone77** [mysteryx93/HanumanInstitute.MvvmDialogs#17]
InitialFile in Dialog settings is not passed to dialog itself.

**Comment by JGKle** [comment]
Same issue here - `InitialFile` has no effect. The real propertyname used by Avalonia is `InitialFileName`.

**Comment by mysteryx93** [comment]
Actually the Avalonia property is `SuggestedFileName`. Can apply that one easily.

`SuggestedStartLocation` isn't being applied either; which takes an `IStorageFolder` instead of a `string`. Will need to think of the proper solution to this.

**Comment by JGKle** [comment]
> Actually the Avalonia property is SuggestedFileName. Can apply that one easily.

Just to clarify: you mean it can't currently be applied, but you'll make it available in a future release?

**Comment by mysteryx93** [comment]
Ya. Made most of the code change already; but will need time to sit down properly and think about the SuggestedFolder issue.

**Comment by JGKle** [comment]
Sounds good. Fwiw just SuggestedFile would be extremely useful tho - the issue with it starting blank is that the user has to explicitly type a filename with the correct extension, otherwise they could save in the wrong format. That's mainly what I was trying to preempt.

**Comment by mysteryx93** [comment]
It's not that simple; I'm asking public feedback and expert review before implementing a solution. It needs to be done right.

https://github.com/AvaloniaUI/Avalonia/discussions/14055

**Comment by mysteryx93** [comment]
It's now fully implemented, along with a complete overhaul and simplification of FileSystem classes.

**Comment by JGKle** [comment]
Nice! Will keep my eyes peeled for when it hits nuget
