### ISSUE TITLE
Failed to generate Java Type for class

### ISSUE THREAD

**Issue by TraZz-Kami** [mysteryx93/HanumanInstitute.MvvmDialogs#18]
Hello, 

I just cloned your repository to learn and try things in samples like the cross-platform one.

But when I tried to launch the Demo.CrossPlatform.Android, it shows me this error: 

> Failed to generate Java type for class: AndroidX.Core.View.Accessibility.AccessibilityManagerCompat/IAccessibilityStateChangeListenerImplementor due to MAX_PATH: System.IO.DirectoryNotFoundException: Impossible de trouver une partie du chemin d'accès 'MyDirectory\HanumanInstitute.MvvmDialogs\samples\Avalonia\CrossPlatform\Demo.CrossPlatform.Android\obj\Debug\net7.0-android\android\src\mono\androidx\core\view\accessibility\AccessibilityManagerCompat_AccessibilityStateChangeListenerImplementor.java'.
   à System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   à System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   à System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   à Microsoft.Android.Build.Tasks.Files.CopyIfStreamChanged(Stream stream, String destination) dans /Users/runner/work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/Files.cs:ligne 170
   à Xamarin.Android.Tasks.GenerateJavaStubs.CreateJavaSources(IEnumerable`1 javaTypes, TypeDefinitionCache cache, MarshalMethodsClassifier classifier)	Demo.CrossPlatform.Android	C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\33.0.68\tools\Xamarin.Android.Common.targets	1476	

I'm using Visual Studio 2022.

**Comment by mysteryx93** [comment]
That's a more generic question. Did you try googling it?

You can also try creating a blank Avalonia cross-platform template and run it. Does that work?

**Comment by TraZz-Kami** [comment]
> 

It was due to the MAX_PATH problem with Windows and Visual Studio. I make it works now ty
