### ISSUE TITLE
Converts AvaloniaUi Sample Music Store App

### ISSUE THREAD

**Issue by TraZz-Kami** [mysteryx93/HanumanInstitute.MvvmDialogs#19]
Hey, I'm trying to create the AvaloniaUI sample Music Store App based on your cross-platform sample because I like the way your MvvmDialogs works.

Everything seems to be fine, except for the album covers. I can't load them without the ViewLocator.cs file from the AvaloniaUI example.

I'm new to this, so if you have any ideas... I'll continue to search! :)

Edit: 

It's not just the album cover; it seems to be an issue with the object as well. I'm getting this: 'MyProjectName.ViewModels.AlbumViewModel' for each music item found during the search. However, I should be getting the cover with the Artist + Title below.

**Comment by mysteryx93** [comment]
What's the actual issue?

The ViewLocator with MvvmDialogs is simplified and easily customizable. It seems you just need to map it to find the proper View for your ViewModel?
