### ISSUE TITLE
MessageBox icon missing

### ISSUE THREAD

**Issue by blahetal** [mysteryx93/HanumanInstitute.MvvmDialogs#2]
Hi, is there a reason for not providing "question mark" icon in MessageBox package (it is in enum `MessageBoxImage`)? It is avaiable in [winforms](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.messageboxicon?view=windowsdesktop-6.0)

**Comment by mysteryx93** [comment]
From your link

> The message box contains a symbol consisting of a question mark in a circle. The question mark message icon is no longer recommended because it does not clearly represent a specific type of message and because the phrasing of a message as a question could apply to any message type. In addition, users can confuse the question mark symbol with a help information symbol. Therefore, do not use this question mark symbol in your message boxes. The system continues to support its inclusion only for backward compatibility.

**Comment by blahetal** [comment]
right, I am used to it in winforms msgboxes :)

**Comment by mysteryx93** [comment]
bad habit according to Microsoft :)
