### ISSUE TITLE
Showing a new window with ShowDialog does not enter DialogFactory.ShowDialog

### ISSUE THREAD

**Issue by Hakoyu** [mysteryx93/HanumanInstitute.MvvmDialogs#20]
Showing a new window with ShowDialog and ShowDialogAsync does not enter DialogFactory.ShowDialog and DialogFactory.ShowDialogAsync
I want to do something with the owner in the ShowDialog
So I'm create new DialogFactory
![image](https://github.com/mysteryx93/HanumanInstitute.MvvmDialogs/assets/48956359/4a4f21fe-47df-4f0d-85bb-f980d0fb8a52)
However, when using ShowDialog, the window can be displayed but the breakpoints cannot be executed.
![image](https://github.com/mysteryx93/HanumanInstitute.MvvmDialogs/assets/48956359/b2f7fc6f-30df-4728-a1b6-41f39895a01f)
Other methods can hit, such as ShowMessageBox.
So how do I implement this?

**Comment by Hakoyu** [comment]
For example, I want to add a blurring effect to the owner when I show dialog, and cancel the blurring effect for the owner after the window is closed.

**Comment by RivenSkaye** [comment]
You could use the available methods on the returned `Task` object to work around this.
```cs
private async void SummonDialog()
{
    BlurMain();
    await ShowDialogAsync(this, new Window1ViewModel()).ContinueWith(_ => { UnBlurMain(); });
}
```

**Comment by mysteryx93** [comment]
`DialogFactory.ShowDialogAsync` is designed for platform dialogs like open/save file.

`DialogManager.ShowDialogAsync` is what you're looking for, and that method is virtual and can be overridden.
