### ISSUE TITLE
Failed to run Avalonia Demo.MessageBox

### ISSUE THREAD

**Issue by Eve-Middleton** [mysteryx93/HanumanInstitute.MvvmDialogs#21]
hello

I am trying to run the project Avalonia Demo.MessageBox, but I have been unable to run successfully.

The error message is shown below. 
![image](https://github.com/mysteryx93/HanumanInstitute.MvvmDialogs/assets/60863436/33d14d65-4913-4acb-8b81-b6e10b4751d6)

I have tried installing the HanumanInstitute through nuget MvvmDialogs; HanumanInstitute MvvmDialogs Avalonia; But it still failed to run

We hope to receive your help. Thank you.

I am using Visual Studio 2022 or Rider 2022.

**Comment by mysteryx93** [comment]
What is the actual error message?

**Comment by Eve-Middleton** [comment]
I tried running it today and found that it can run successfully in Rider2022, without any modifications, which is strange. Thank you for your reply, wish you all the best.

**Comment by mysteryx93** [comment]
Sometimes you may need to clear bin/obj folders or something to fix bugs
