### ISSUE TITLE
Not working dialogService.ShowOpenFileDialogAsync inside of FluentAvaloniaUI NavigationView

### ISSUE THREAD

**Issue by rychlym** [mysteryx93/HanumanInstitute.MvvmDialogs#22]
Hi,
I have tried to learn  AvaloniaUI  and came across an issue with these common file/folder dialog boxes. Finally I tried to create a test app from scratch again to test it, where I could reproduce it (see the screenshot).
The app has utilized the both message box an the file/folder dialogs and the message box works well for the both main window view model and view model navigated using  FluentAvaloniaUI NavigationView.
However, the common file/folder dialog boxes works only in the MainWindow view model, not in the  view model navigated using FluentAvaloniaUI NavigationView, which end up with the ArgumentException, "No view found with specified ownerViewModel of type AvaloniaDialogsTest.ViewModels.Category1ViewModel." 

Thinking (not so deeply :) if one kind of dialog work for both cases and the second one only for one case - sounds like an insufficient handling of such situation or a bug.
But it is not so easy - I can see that documentation told about possibility to use various pre-prepared view locators.
Well, for me it is not so easy to see which ViewLocator to use or how implement a custom one for this special case (having  common file/folder dialog boxes in both main view model and in viewmodel navigated from it or at least for the navigated  view models).? Could you please help?

some details: (if a need, I could attach the whole test app solution ):

- I am using AvvaloniaUI 11.0.4, FluentAvaloniaUI 2.0.4(, CommunityToolkit.Mvvm 8.2.1), MvvmDialogs.Avalonia.MessageBox, MvvmDialogs.Avalonia.Fluent 2.0.0, Splat 14.7.1
- the main is calling BuildAvaloniaApp().StartWithClassicDesktopLifetime(args);
- App.Initialize() part:
            build.RegisterLazySingleton(() => (IDialogService)new DialogService(
                    new DialogManager(
                        viewLocator: new ViewLocator(),
                        dialogFactory: new DialogFactory()
                                           .AddMessageBox()
                                           .AddFluent(FluentMessageBoxType.ContentDialog)),
                    viewModelFactory: x => Locator.Current.GetService(x)));

            // manually register the view models
            build.Register(() => new NavViewModel());
            build.Register(() => new MainWindowViewModel(resolver.GetRequiredService<IDialogService>(), resolver.GetRequiredService<NavViewModel>()));
- call of the Category1ViewModel(resolver.GetRequiredService<IDialogService>())  from the NavViewModel()
- the  ViewLocator inherits from your ViewLocatorBase based on your docs  (also tried some tweaks there but without any success) 

The exception stack trace - (can see it is a kind of  StartWithClassicDesktopLifetime)
   at HanumanInstitute.MvvmDialogs.DialogManagerBase`1.<>c__DisplayClass30_0`1.<<ShowFrameworkDialogAsync>b__0>d.MoveNext()
   at HanumanInstitute.MvvmDialogs.DialogManagerBase`1.<ShowFrameworkDialogAsync>d__30`1.MoveNext()
   at HanumanInstitute.MvvmDialogs.DialogServiceExtensions.<ShowOpenFilesDialogAsync>d__3.MoveNext()
   at HanumanInstitute.MvvmDialogs.DialogServiceExtensions.<ShowOpenFileDialogAsync>d__2.MoveNext()
   at AvaloniaDialogsTest.ViewModels.Category1ViewModel.<GetFilePath>d__7.MoveNext() in C:\Users\mr\source\repos\my\UI\Avalonia\AvaloniaDialogsTest\AvaloniaDialogsTest\ViewModels\Category1ViewModel.cs:line 67
   at AvaloniaDialogsTest.ViewModels.Category1ViewModel.<SetFilePath>d__6.MoveNext() in C:\Users\mr\source\repos\my\UI\Avalonia\AvaloniaDialogsTest\AvaloniaDialogsTest\ViewModels\Category1ViewModel.cs:line 48
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.SendOrPostCallbackDispatcherOperation.InvokeCore()
   at Avalonia.Threading.DispatcherOperation.Execute()
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job)
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore(Boolean fromExplicitBackgroundProcessingCallback)
   at Avalonia.Threading.Dispatcher.Signaled()
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32DispatcherImpl.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode)
   at AvaloniaDialogsTest.Program.Main(String[] args) in C:\Users\mr\source\repos\my\UI\Avalonia\AvaloniaDialogsTest\AvaloniaDialogsTest\Program.cs:line 12

The test app screenshot:
![image](https://github.com/mysteryx93/HanumanInstitute.MvvmDialogs/assets/11144487/94bcf1aa-400f-4aeb-9e01-de937164e3ab)

**Comment by mysteryx93** [comment]
If you want to show from a ViewModel that is not the main window, then you need a "Owner" property on that ViewModel holding a reference to the parent ViewModel.

Then you'll show it using Owner.

**Comment by rychlym** [comment]
yes, thanks a lot -  passing of the current main window view model has helped

in detail:
a) registration (to be 
            build.RegisterLazySingleton(() => new MainWindowViewModel(resolver.GetRequiredService<IDialogService>(), resolver.GetRequiredService<NavViewModel>()));

b) in the  other view models i:
            var mainViewModel = Locator.Current.GetRequiredService<MainWindowViewModel>();
            var fileName = await dialogService.ShowOpenFileDialogAsync(mainViewModel, settings);



I have found a different "quick" solution of this meanwhile: a small override of the Dialog manager + ViewLocator dirty tweaks to hold the cache of the view model views...

public class FluentDialogManager : DialogManager
{
    public FluentDialogManager()
    {        
    }

    public FluentDialogManager(IViewLocator? viewLocator = null, IDialogFactory? dialogFactory = null, ILogger<DialogManager>? logger = null, IDispatcher? dispatcher = null, Control? customNavigationRoot = null)
    :base(viewLocator, dialogFactory, logger, dispatcher, customNavigationRoot)
    { }

    public override IView? FindViewByViewModel(INotifyPropertyChanged viewModel)
    {
        var baseValue = base.FindViewByViewModel(viewModel);
        if (baseValue != null) return baseValue;

        // if the base algorithm does not work, use the view locator cache...
        Ut.ViewLocator.Cache.TryGetValue(viewModel, out var control);
        var view = this.AsWrapper(control as ContentControl);
        return view;
   }

**Comment by mysteryx93** [comment]
You might run into the problem that you get the View as a Control, and not as a TopModel. If that's the case, then you cannot set a regular Control as a window owner.

**Comment by Ricent82** [comment]
I'm having this issue too, and still get `No view found with specified ownerViewModel of type` even if I pass the MainViewModel. 

I started with an app where MainViewModel/MainView was the main and only control/viewModel. Dialog prompting worked. Then I extract a bit of it into a separate UserControl - so within MainView, I now have i.e.

```
<local:HomeTabView>
  <local:HomeTabView.DataContext>
    <local:HomeTabViewModel/>
  </local:HomeTabView.DataContext>
</local:HomeTabView>
```

And whereas in MainViewModel I previously had:

```
var result = await _dialogService.ShowOpenFileDialogAsync(this, settings);
```

I get the error, so I change to:

```
var result = await _dialogService.ShowOpenFileDialogAsync(App.MainViewModel, settings);
```
where in App.cs, MainViewModel is just a static property that saves the viewmodel used in:
```
DialogService.Show(null, MainViewModel);
```

However, whether I pass `App.MainViewModel` or `this` to `_dialogService.ShowOpenFileDialogAsync` in `HomeTabView`, it throws that error. If I call `_dialogService.ShowOpenFileDialogAsync` from MainViewModel, it works. I also tried adding an Owner property to HomeTabViewModel as suggested, and setting it to `App.MainViewModel`, but the result is the same.

**Comment by mysteryx93** [comment]
If you pass Owner to the other ViewModel, then the call should be exactly the same, passing the same parent ViewModel, so why would it fail?

**Comment by Ricent82** [comment]
You're right, it's super odd.

Did some more investigating - here's a way you can repro nearly the exact behavior in the MVVMDialogs sample code:

* Open the `Demo.FluentContentDialog` project & go to `MainViewModel.cs`
* Change any of the instances of `_dialogService.ShowContentDialogAsync(this, settings)` to `_dialogService.ShowContentDialogAsync(App.MainWindow, settings)`
* Try to open the dialog, You'll get the `No view found with specified ownerViewModel of type Demo.Avalonia.FluentContentDialog.MainWindowViewModel`

So it seems if I directly pass `App.MainWindow` (which is actually the `MainWindowViewModel`), it fails - even though that should be the same...?

**Comment by mysteryx93** [comment]
App.MainWindow is a View and not a ViewModel

App.MainWindow.DataSource should give you the ViewModel

**Comment by Ricent82** [comment]
It sure looks like a ViewModel, not a View, based on the code: 

![2023-12-16 07 34 00](https://github.com/mysteryx93/HanumanInstitute.MvvmDialogs/assets/73326913/aded37e7-98f7-4ea7-a893-09322fff52c5)

And App.MainWindow.DataSource doesn't exist.

And if you stop the bugger & examine App.MainWindow, you'll see that it's definitely a ViewModel, not a View.

**Comment by mysteryx93** [comment]
Ah was missing the definition. If you call `App.MainWindow`, you get a NEW instance of the ViewModel, not the one that was displayed.

Perhaps changing the convention to something like `CreateMainWindow` could avoid this kind of confusion.

**Comment by Ricent82** [comment]
Hmm, if that's the case, should probably be called `CreateMainWindowViewModel`, since it's actually an instance of the VM, not the Window (view) - even you were confused by that ;)

I thought the whole point of `Locator.Current.GetService` was dependency injection tho, so you could share a service across various parts of the app without needing to pass around a reference - if it's just an entirely new instance each time, how could that even work? Still seems a bit strange...?

**Comment by mysteryx93** [comment]
Dependency Injection, you decide whether you want Singleton (single instance for whole app) or an instance each time. For "Customer Details", you'll want a separate instance on each call.

`CreateMainWindowViewModel` just a bit long for my taste; anyway doesn't make much of a difference.

**Comment by Ricent82** [comment]
Aha, I see - `Locator.CurrentMutable.RegisterConstant` vs `Locator.CurrentMutable.Register`.

In that case, for the purpose of these ViewModels, maybe rather than changing the static property to `Createxxx`, it'd be cleaner/more intuitive to just register them as singletons, no?

**Comment by mysteryx93** [comment]
You shouldn't be calling the Locator directly from your code usually; and if you register as Singleton, you'll get issues in the cases where you need multiple instances.

**Comment by Ricent82** [comment]
Right, I just meant in *this* case - for the public static properties that are storing references to locators that create new instances.

**Comment by mysteryx93** [comment]
ok actually this case is one of the rate situations where calling the Locator from the code is OK; although you won't call it directly, but via IDialogService.

If you have a detail view that requires multiple instances, you'll run into trouble if you set them as Singleton.

And creating the ViewModel for the new View is the only time you should ever call it; you should never call the Locator from your code otherwise, otherwise you'll be unable to write unit tests.

**Comment by Ricent82** [comment]
> If you have a detail view that requires multiple instances, you'll run into trouble if you set them as Singleton.

I just meant for the MainViewModel (not for all). Since there should only ever be one MainViewModel, right? And the dialogs class requires referring to it (to set it as the owner) anytime you want to show a dialog. Thus, it seems like it'd be both much clearer & more convenient if *just* MainViewModel were registered as a singleton - thus the sample code becomes `_dialogService.ShowContentDialogAsync(App.MainViewModel, settings)`, and works from everywhere. No more confusion when trying to show it from another viewmodel. Right?

**Comment by mysteryx93** [comment]
Well... if you decide that MainView will always be the parent of every dialog in your application, maintaining a static or singleton reference to it can be an option... although it's not a very clean design

**Comment by Ricent82** [comment]
Gotcha. Anyway, looks like it's all solved now - the issue was just that that global App.MainView(model) was creating fresh new instances each time. So...solved - thanks again! :)

**Comment by rychlym** [comment]
Hi, I was playing with another application having a Mainwindow antd then a MainView with a navigagion TabControl (Something similar to the demo app within the https://github.com/irihitech/Semi.Avalonia)

Well after an investigation I have found that the DialogManager could be somehow simplified

`
public override IView? FindViewByViewModel(INotifyPropertyChanged viewModel)
{
  if (_useNavigation)
  {
    return _navigationManager!.GetViewForViewModel(viewModel).AsWrapper(_navigationManager, View_Closing);
  }
  else
  {
    var windows =  Windows.ToList();
    var window = windows.Count == 1
          ? windows[0]
          : windows.FirstOrDefault(x => ReferenceEquals(viewModel, x.DataContext));
    return window.AsWrapper();
  }
}

`
Well it looks it is again not so clean solution... :(
However, I have right one window in my case and I believe it would simply working for my all cases I have met :) 

Can I ask some questions?: 
1a) Is the viewModel used in the different parts of the code since passed to the ShowOpenFileDialogAsync?
1b) And the same question about usage of the viewModel  in different parts of the code, if the _useNavigation is set to true 
 (I was thinking if even to create a similar method without that parameter)

2 ) What circumstances can the Windows enumeration have more items at?

**Comment by mysteryx93** [comment]
I'm not sure I understand your questions correctly.

> 1a) Is the viewModel used in the different parts of the code since passed to the ShowOpenFileDialogAsync?

ViewModel is only used to find the View to assign as parent.

> 1b) And the same question about usage of the viewModel in different parts of the code, if the _useNavigation is set to true

I don't remember off the top of my head how parent is set in Android apps where there is no Window. You can investigate the code if you need that info.

> 2 ) What circumstances can the Windows enumeration have more items at?

When there are several Windows displayed in desktop applications.

**Comment by mysteryx93** [comment]
I will note that for single-view applications, the parent ViewModel affects the navigation order when closing a view.

**Comment by rychlym** [comment]
Thanks a lot for your answers! My questions  tried to lead to an idea, that in case of one window app, the consumers could't be bothered by that MainViewModel argument at all, when a need to call the Show... DialogAsync(). A similar simplification could be, that the consumer would  control the index to the Windows ... So, finally, it could lead to exposing overriden methods like ShowDialog.. Async(.. , int windowIndex = 0)  again, without the wiew model parameter. What do you think about it?
