### ISSUE TITLE
Provide sync methods for dialogs

### ISSUE THREAD

**Issue by virzak** [mysteryx93/HanumanInstitute.MvvmDialogs#23]
First of, thanks for this library. Trying it out for the first time and this is exactly what I asked for https://github.com/FantasticFiasco/mvvm-dialogs/issues/177

While trying to make the dialog logic framework agnostic, I'm forced to make dialog calls async. Why is the async option only available for WPF?

**Comment by mysteryx93** [comment]
Dialogs are an async operation by nature, and most other UIs expose async methods. Only WPF pre-dates the async era and has sync methods instead; I added sync methods to WPF just to make it easier to port existing code.

**Comment by virzak** [comment]
Makes sense and thanks again.

**Comment by UEPSs** [comment]
Under certain conditions(e.g. in event handler), async call is not supported and sync call is needed. how to solve? @mysteryx93

**Comment by mysteryx93** [comment]
https://siderite.dev/blog/how-to-use-await-in-event-handlers/
