### ISSUE TITLE
Consider changing List<FileFilter> to another type

### ISSUE THREAD

**Issue by virzak** [mysteryx93/HanumanInstitute.MvvmDialogs#24]
Using List<T> in an API causes [ca1002](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1002)

Consider switching to IList perhaps?

This also propagates to user code when filters are reused:

```cs
public static readonly List<FileFilter> Csv = [new("Comma separated file (*.csv)", ["csv"])];
```
![image](https://github.com/mysteryx93/HanumanInstitute.MvvmDialogs/assets/6209775/954bbd7c-2116-4451-9b2c-9cd100bbab26)

**Comment by mysteryx93** [comment]
Ok changed. Looks like that's the only place where it slipped out.
