### ISSUE TITLE
Proper use of dialogService.ShowOpenFileDialogAsync

### ISSUE THREAD

**Issue by msh2050** [mysteryx93/HanumanInstitute.MvvmDialogs#25]
I'm using Avalonia 11.05 with .net7 the `result.OpenReadAsync()` is working with desktop and Android but not with the Web platform.
how can I check if the file is loaded successfully?
And in the case of larga file, how I can read the file uploading status.

```c#
private async Task OpenFileAsync()
{
   
    var settings = GetSettings(false);
    var result = await _dialogService.ShowOpenFileDialogAsync(this, settings);
    
    if (result?.Path != null)
    { 
        using var stream =  result.OpenReadAsync();
        
        ReadExcel(stream.Result);
    }

}
```

**Comment by mysteryx93** [comment]
I've just fixed the Web demo so it at least runs... it's going to require a little bit of work

**Comment by mysteryx93** [comment]
Browser app really isn't behaving well.

Posted some issues there
https://github.com/AvaloniaUI/Avalonia/issues/14065

**Comment by msh2050** [comment]
I managed to make it work with the browser and I added the upload status
this is my code `maybe you  need to remove some extra code that I add for my specific needs'
```c#
var ms = new MemoryStream();
var settings = GetSettings();
var result = await _dialogService.ShowOpenFileDialogAsync(this, settings);
IProgress<long> progress = new SynchronousProgress<long>(value =>
{
    ProgressBarCurrentValue = value;
    StatusText = value.ToString();
});

if (result?.Path != null)
{

    StatusText = result.Name;
    using var stream = result.OpenReadAsync();
    StatusText += " Open Read Done";
    //await stream.Result.CopyToAsync(ms);
    await stream.ContinueWith(async t =>
    {

        StatusText += " getting the result";
        var streamResult = t.Result;
        StatusText += " Result size: " + streamResult.Length + " starting copy to memory";
        await streamResult.CopyToAsync(ms, progress, source.Token, 1024);
        StatusText += "Done";
        ms.Position = 0;
        StatusText += " size:" + ms.Length;
        await ReadExcel(ms).ConfigureAwait(false);

    });



}
```

**Comment by mysteryx93** [comment]
Oh perfect!

I'll add this to the samples.

**Comment by mysteryx93** [comment]
btw where do you get your `source.Token`?

**Comment by msh2050** [comment]
> btw where do you get your `source.Token`?

static readonly CancellationTokenSource source = new ();

**Comment by mysteryx93** [comment]
you just created your own to have a cancel button?

**Comment by msh2050** [comment]
> You just created your own to have a cancel button?

yes, but I have not implemented it yet.
I just want to test this but I may not need it since I have no large files  to upload
