### ISSUE TITLE
Owner must be of type Window exception, on Android only

### ISSUE THREAD

**Issue by Ricent82** [mysteryx93/HanumanInstitute.MvvmDialogs#26]
Hi,

I'm using this package successfully on both Windows & Android to show both "open" and "save" dialogs from my main viewmodel:

```
var result = await _dialogService.ShowOpenFileDialogAsync(this, settings); // works
var result = await _dialogService.ShowSaveFileDialogAsync(this, settings); // works
```

However, the following only works on Windows:
```
await _dialogService.ShowMessageBoxAsync(this, "Test Notification", "Error", MessageBoxButton.Ok);
```
The same code on Android throws `System.InvalidCastException: 'Owner must be of type Window.'` If I set a breakpoint right before, I can confirm that the "this" object is the ViewModel - same as both of the calls above. What might I be missing?

Thanks in advance

**Comment by Ricent82** [comment]
...Oh wait, I think I see in the main docs that messageboxes are supported on desktop only. Is that the case?

If so, can close this issue - just with the suggestion that it throw a more specific/clear error message ("Messageboxes are only supported on desktop"), if that's the case?

**Comment by mysteryx93** [comment]
There is no standard MessageBox in Avalonia, you can configure one of various options available. For Android, you'll need to configure an android-compatible implementation.

**Comment by Ricent82** [comment]
Got it, thanks. I suppose then that this is just a suggestion for a clearer error - `System.InvalidCastException: 'Owner must be of type Window.'` is pretty unclear/ambiguous, it'd probably be lower friction for new users if it threw something with a specific message, i.e. `Avalonia.MessageBox is only supported on Desktop - use Avalonia.Fluent or Avalonia.DialogHost to support mobile.`

...Or better yet, rather than having the default usage in the docs be Avalonia.MessageBox, just start with one of the options that does support all platforms out of the box.

**Comment by mysteryx93** [comment]
Do note that `Avalonia.MessageBox` also supports Popup mode, which should work on Android

**Comment by Ricent82** [comment]
Then in that case, perhaps that could be the sample code. Or the existing sample code to have a note: "This sample code isn't supported on Android - if you want to support Android, it should be changed as follows"

**Comment by mysteryx93** [comment]
This should do the trick..

```
public static IDialogFactory AddMessageBox(this IDialogFactory factory, MessageBoxMode mode = MessageBoxMode.Window)
{
    if (Application.Current?.ApplicationLifetime is ISingleViewApplicationLifetime && mode == MessageBoxMode.Window)
    {
        throw new NotSupportedException("Avalonia.MessageBox with mode=Window is only supported in Desktop applications. Consider using mode=Popup or a different MessageBox implementation.");
    }
    return new MessageBoxDialogFactory(factory)
    {
        Mode = mode
    };
}
```
