### ISSUE TITLE
FileFilter unworking on Android

### ISSUE THREAD

**Issue by JGKle** [mysteryx93/HanumanInstitute.MvvmDialogs#28]
The following code:

```
var settings = new OpenFileDialogSettings
{
    Filters = new List<FileFilter>()
    {
        new FileFilter("Text Files", new[]{"txt"})
    }
};
var result = await _dialogService.ShowOpenFileDialogAsync(this, settings);
```

On Windows, successfully shows an OpenFile dialog that only allows you to select text files. On Android, it allows you to select anything. Seems like the FileFilter is unworking on mobile. Is that unsupported?

**Comment by mysteryx93** [comment]
Android and iOS use MEME type instead
https://docs.avaloniaui.net/docs/concepts/services/storage-provider/file-picker-options

**Comment by JGKle** [comment]
Ahh - gotcha, thanks
