### ISSUE TITLE
Breaks AOT on Android

### ISSUE THREAD

**Issue by JGKle** [mysteryx93/HanumanInstitute.MvvmDialogs#29]
It appears that creating the main view per the documentation:

```
GC.KeepAlive(typeof(DialogService));
dialogService.Show(null, MainViewModel);
```

...breaks AOT on Android (the app crashes immediately on launch). Replacing the above code with the original Avalonia initialization code fixes it:

```
if (ApplicationLifetime is IClassicDesktopStyleApplicationLifetime desktop)
{
    desktop.MainWindow = new MainWindow
    {
        DataContext = new MainViewModel()
    };
}
else if (ApplicationLifetime is ISingleViewApplicationLifetime singleViewPlatform)
{
    singleViewPlatform.MainView = new MainView
    {
        DataContext = new MainViewModel()
    };
}
```

For performance reasons, we really need AOT to work on our production builds. Is it possible to use MvvmDialogs without breaking AOT?

**Comment by JGKle** [comment]
Extra notes: 
* Have tried <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
* The only "Trimming Granularity" that isn't deprecated is now "Link"
* Most likely the issue is use of Reflection. There's a lot of discussion about this on the Avalonia forums. It might be possible to directly reference whatever code is being invoked via reflection, to ensure that it doesn't get trimmed. Or to explicitly list it in a roots.xml file. Some examples: https://github.com/AvaloniaUI/Avalonia/issues/9380, https://github.com/AvaloniaUI/Avalonia/issues/12419, https://github.com/AvaloniaUI/Avalonia/issues/10069
* Here's docs on AOT: https://learn.microsoft.com/en-us/dotnet/core/deploying/native-aot/?tabs=net7%2Cwindows

**Comment by mysteryx93** [comment]
I've successfully deployed on Windows/Linux with AOT. The only place where reflection could be used is the default reflection-based ViewLocator, otherwise there is no reflection.

Oh wait -- are you using the default ViewLocator? You'll need to use the StrongViewLocator.

**Comment by JGKle** [comment]
That was it, thanks for the super quick reply! I searched the github issues & readme for "AOT" but not for "Trimming", so I didn't see that note - dang.  Maybe AOT would be a good keyword to stick there in the readme, too :)
