### ISSUE TITLE
MessageBox - long text is truncated

### ISSUE THREAD

**Issue by blahetal** [mysteryx93/HanumanInstitute.MvvmDialogs#3]
Hi,
it looks to me that MessageBox does not properly handle long texts.
The following MsgBox text has three lines and the third line is truncated to "Alfa_k must be between 30 and". The last few characters are missing. Can you check it please. 

`await _dialogService.ShowMessageBoxAsync(this, new MessageBoxSettings() { Button = MessageBoxButton.Ok, Icon = MessageBoxImage.Warning, DefaultValue = true, Text = $"Zadané hodnoty nejsou validní.\n\nAlfa_k must be between 30 and 90", Title = "test" });`

**Comment by mysteryx93** [comment]
That's an issue with Avalonia.MessageBox. There has been several attempts to fix it but none has been fully successful.

https://github.com/AvaloniaCommunity/MessageBox.Avalonia/issues/84

The only thing that this library does is to add a line break to the messages to lessen the issue.

FluentAvalonia messageboxes should not have those issues.
