### ISSUE TITLE
ViewModelFactory with MVVM Toolkit

### ISSUE THREAD

**Issue by mayka-mack** [mysteryx93/HanumanInstitute.MvvmDialogs#30]
This is definitely operator error, but I was hoping you may be able to assist in what is wrong with my setup. I am using MvvmDialogs with Avalonia and MVVM Toolkit, but when I tried adapting one of your examples, I keep getting the following error. I think it's not able to find the view model using the view model factory, but I can't figure out why.

`System.NullReferenceException: 'ViewModelFactory was not set in the DialogService constructor or the function returned null for type 'DialogExample.AskTextBoxViewModel'.'`

[DialogExample.zip](https://github.com/mysteryx93/HanumanInstitute.MvvmDialogs/files/14066721/DialogExample.zip)

**Comment by mysteryx93** [comment]
Can you confirm whether ViewModelFactory is set in the DialogService constructor? The error is pretty straightforward and detailed, you can probably debug it from there.

**Comment by mayka-mack** [comment]
I think perhaps it might not be. When stepping through where the code errors, I eventually get this error from within System.Private.Core.Lib's ValueStringBuilder AppendFormat:
```
▶ | RawChars | "ViewModelFactory was not set in the DialogService constructor or the function returned null for type 'w\0忠ﲫɓ\0\u0001\0ɓ\0\ud9d0预翻\0预翻\0껨ﲩɓ\0歰翻\0껨ﲩɓ\0\0\0\0\0忠ﲫɓ\0\u0001\0w\0预翻\0预翻\0\0\0\0\0\u0004\0\0耀\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0Ȃ\0\0\0\0\0\0\0厰͖ɔ\0뙵翻\0랸\udf17w\0㿠馳翻\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"
```
Is there a good way to tell **why** it is not getting set? Trying to really understand how this all works so that I can use the library more effectively. This is how I have it in the `DialogService` constructor:
```
public override void OnFrameworkInitializationCompleted()
{
    if (ApplicationLifetime is IClassicDesktopStyleApplicationLifetime desktop)
    {
        // Line below is needed to remove Avalonia data validation.
        // Without this line you will get duplicate validations from both Avalonia and CT
        BindingPlugins.DataValidators.RemoveAt(0);

        desktop.MainWindow = new MainView();

        Ioc.Default.ConfigureServices(
            new ServiceCollection()
                .AddSingleton<IDialogService>(
                        new DialogService(
                            new DialogManager(
                                viewLocator: new ViewLocator(),
                                dialogFactory: new DialogFactory().AddFluent()
                            ),
                            viewModelFactory: x => Ioc.Default.GetService(x)
                        )
                )
                .AddTransient<MainViewModel>()
                .BuildServiceProvider()
        );

        desktop.MainWindow.DataContext = Ioc.Default.GetService<MainViewModel>();
    }

    base.OnFrameworkInitializationCompleted();
}
```

**Comment by mysteryx93** [comment]
OK ViewModelFactory is set to `x => Ioc.Default.GetService(x)`

WTF is wrong with the data type of the object being passed?????

Set a breakpoint into `x => Ioc.Default.GetService(x)` and figure out what's being passed there.

**Comment by mysteryx93** [comment]
Well actually what gets passed to it is what you pass when calling `DialogService.GetViewModel()`, this does nothing more than forward the call.

You're passing in something really funky to it.

In fact, instead of calling `GetViewModel`, you could call your IOC directly instead; but you'd then run into issues designing unit tests.

**Comment by mayka-mack** [comment]
@mysteryx93 I think I finally figured it out! I had to directly add a reference to the AskTextBoxViewModel, and now it is able to find it.

I really appreciate all your help with this! I was well and truly stuck. Thank you for making this amazing package!!!
```
Ioc.Default.ConfigureServices(
    new ServiceCollection()
        .AddSingleton<IDialogService>(
                new DialogService(
                    new DialogManager(
                        viewLocator: new ViewLocator(),
                        dialogFactory: new DialogFactory().AddFluent()
                    ),
                    viewModelFactory: x => Ioc.Default.GetService(x)
                )
        )
        .AddTransient<MainViewModel>()
        .AddTransient<AskTextBoxViewModel>()
        .BuildServiceProvider()
);
```

Edit: I think what I was missing is that the ReactiveUI examples have splat registrations to the view models. Since I'm using MVVM Toolkit, I had to add a transient reference. Putting the explanation here in case it helps anyone else in the future.
