### ISSUE TITLE
Optionally use DialogHost when calling ShowDialog

### ISSUE THREAD

**Issue by nixtar** [mysteryx93/HanumanInstitute.MvvmDialogs#31]
Hello,

Thanks for your work on this library, it's very awesome ❤️.

I have a scenario where I have a WPF and Avalonia version of my app and they share a common library that contains all the Viewmodels etc.
In the Avalonia app I have a view that I want to display using DialogHost however as there is no equal in WPF I can't call ShowDialogHostAsync from the VMs.

I'd like a way to use DialogHost for ShowDialogAsync calls.

One example I can think of is to allow an app wide config of common DialogHostSettings during the `.AddDialogHost()` call and if the ViewLocator finds a `TNavView` it uses that instead of the desktop view.

Thanks,
Nick

**Comment by mysteryx93** [comment]
Since you could need to display both real dialogs and DialogHost box, I think you're better to use a differerent function for it. You can add your own extension method, available for both Avalonia and WPF, that redirects the call to the appropriate method depending on the platform.

**Comment by nixtar** [comment]
Ahh that's a good idea! 👍

If I remember I'll update this with a snippet of what I come up with in case someone else has this idea, but in the meantime, I'll close this off.
