### ISSUE TITLE
Use OpenDialogHostAsync from any place

### ISSUE THREAD

**Issue by Guddiny** [mysteryx93/HanumanInstitute.MvvmDialogs#33]
Is it Possible to use `OpenDialogHostAsync` from any `ViewModel` passed as parent?
For me it doesn't work with exception
`No view found with specified ownerViewModel of type .... ` 
but works well if i call dialog service from `MainWindowViewModel` 
Thanks.

**Comment by mysteryx93** [comment]
Your ViewModel should contain a Parent property that contains the parent ViewModel, then you can use it to show the dialog.

**Comment by Guddiny** [comment]
OK . Understood. Thank you.
