### ISSUE TITLE
Change color button "Yes" inside MessageBox

### ISSUE THREAD

**Issue by TraZz-Kami** [mysteryx93/HanumanInstitute.MvvmDialogs#35]
Hello, I'm enjoying your work, but I can't find how to change the color of the "Yes" button when calling this:

bool userConfirmed = (bool)await _dialogService.DialogManager.ShowFrameworkDialogAsync(this, messageBoxSettings);

I've set every button inside my app to green, but this one doesn't change, and I can't figure out why.

Example : 
![image](https://github.com/mysteryx93/HanumanInstitute.MvvmDialogs/assets/58888326/dd5fe13f-b425-490e-958e-977d95584017)

Do you know why ?

**Comment by mysteryx93** [comment]
Which message box implementation are you using? You'll need to look into the documentation of that specific message box provider. Perhaps even try using it manually to customize the styles before adding MvvmDialogs. This library only forwards the calls but is in no way involved in the styling.
