### ISSUE TITLE
Build howto

### ISSUE THREAD

**Issue by KluDev** [mysteryx93/HanumanInstitute.MvvmDialogs#5]
It would be nice to have a build howto page. 

- What should be installed first
- What version of SDKs and other things to use
- Where to download the prerequisites

Thanks

**Comment by mysteryx93** [comment]
It's really just open the project and compile... is there anything causing issues?

**Comment by KluDev** [comment]
Yes, I have the folowing error if I use the build.ps1 script:

> PS D:\Sources\HanumanInstitute.MvvmDialogs\build> .\build.ps1
> Preparing to run build script...
> Running build script...
> The 'addin' directive is attempting to install the 'Cake.FileHelpers' package
> without specifying a package version number.
> More information on this can be found at https://cakebuild.net/docs/writing-builds/reproducible-builds/
> It's not recommended, but you can explicitly override this warning
> by configuring the Skip Package Version Check setting to true
> (i.e. command line parameter "--settings_skippackageversioncheck=true",
> environment variable "CAKE_SETTINGS_SKIPPACKAGEVERSIONCHECK=true",
> read more about configuration at https://cakebuild.net/docs/running-builds/configuration/)
> **Error: Failed to install addin 'Cake.FileHelpers'.**
> PS D:\Sources\HanumanInstitute.MvvmDialogs\build>

There is an error with the install of 'Cake.FileHelpers' addin.

**Comment by mysteryx93** [comment]
that build folder is probably remnants of the code-base I started from, it's not good. I'll have to delete that folder.

**Comment by KluDev** [comment]
OK, so please delete the folder. With VS it works.
