### ISSUE TITLE
No view found with specified ownerViewModel of type "..."

### ISSUE THREAD

**Issue by Crauzer** [mysteryx93/HanumanInstitute.MvvmDialogs#6]
Project structure:
![image](https://user-images.githubusercontent.com/18646077/211155156-2a266a1a-d1b3-4547-8b08-3ad9d3b1bcf0.png)

I'm using the default `ViewLocator`, any idea what the issue could be ?
The documentation for this library is not really good as it doesn't demonstrate how to properly structure your project
I've been trying to solve this error for at least 4 hours now and I have no idea why it isn't working, I've tried everything...

**Comment by Crauzer** [comment]
FYI: I'm trying to open a file dialog from `SkinnedMeshToGltfViewModel` using an extension method from `DialogExtensions`.

```cs
public static async Task<(string path, SkinnedMesh skinnedMesh)> ShowLoadSkinnedMeshViewAsync(
    this IDialogService dialogService,
    INotifyPropertyChanged ownerViewModel
)
{
    Guard.IsNotNull(dialogService, nameof(dialogService));
    Guard.IsNotNull(ownerViewModel, nameof(ownerViewModel));

    string? result = await dialogService.ShowOpenFileDialogAsync(
        ownerViewModel,
        new()
        {
            AllowMultiple = false,
            Title = "aaa",
            Filters = new() { new("Simple Skin files (.skn)", new[] { "skn" }) }
        }
    );

    return (result!, SkinnedMesh.ReadFromSimpleSkin(result!));
}
```

```cs
private async Task<(string path, SkinnedMesh skinnedMesh)> LoadSimpleSkin()
{
    var x = this._dialogService.ShowLoadSkinnedMeshViewAsync(App.MainWindow);

    return await x;
}
```

**Comment by Crauzer** [comment]
This is my `App.axaml.cs`:
```cs
public partial class App : Application
{
    public static MainWindowViewModel MainWindow => Locator.Current.GetService<MainWindowViewModel>()!;

    public override void Initialize()
    {
        AvaloniaXamlLoader.Load(this);

        ILoggerFactory? loggerFactory = LoggerFactory.Create(
            builder => builder.AddFilter(logLevel => true).AddDebug()
        );

        Locator.CurrentMutable.RegisterLazySingleton(
            () =>
                (IDialogService)
                    new DialogService(
                        new DialogManager(
                            viewLocator: new ViewLocator(),
                            logger: loggerFactory.CreateLogger<DialogManager>()
                        ),
                        viewModelFactory: x => Locator.Current.GetService(x)
                    )
        );

        SplatRegistrations.Register<MainWindowViewModel>();
        SplatRegistrations.SetupIOC();
    }

    public override void OnFrameworkInitializationCompleted()
    {
        GC.KeepAlive(typeof(DialogService));

        if (ApplicationLifetime is IClassicDesktopStyleApplicationLifetime desktop)
        {
            desktop.MainWindow = new MainWindow { DataContext = MainWindow, };
        }

        base.OnFrameworkInitializationCompleted();
    }
}
```

**Comment by Crauzer** [comment]
It seems like the library is somehow unable to find the MainWindow:
https://github.com/mysteryx93/HanumanInstitute.MvvmDialogs/blob/ec321acc457d4a326268b3ab3e29cb88940b2d65/src/MvvmDialogs.Wpf/DialogManager.cs#L56-L61

I don't understand why that's the case though, since the `DataContext` of the `MainWindow` is set to `App.MainWindow` which is registered as a singleton

**Comment by mysteryx93** [comment]
By default it's looking for MainView.

Are you using the latest Preview or the stable version?

The Preview version has partial implementation to support mobile and I made considerable changes to the factories and locators. It might not look for MainWindow by default yet. I'm not exactly sure of the current state of the Locator in the Preview version as that code is not completed.

**Comment by mysteryx93** [comment]
A new preview version has been released and documentation is now updated.

**Comment by lxymahatma** [comment]
Same problem

Avalonia Version: 11.0.0-rc1.1

Package Version: 
HanumanInstitute.MvvmDialogs.Avalonia: 2.0.0-rc1
HanumanInstitute.MvvmDialogs.Avalonia.DialogHost

The code which causes the error
![image](https://github.com/mysteryx93/HanumanInstitute.MvvmDialogs/assets/66151783/5a2a8ae8-faec-416f-b92d-70b4748d94c1)

I use autofac to do the dependency injection
![image](https://github.com/mysteryx93/HanumanInstitute.MvvmDialogs/assets/66151783/82a3f155-beb8-4d53-8d36-b0111828b671)

ViewLocator Class:
![image](https://github.com/mysteryx93/HanumanInstitute.MvvmDialogs/assets/66151783/fdb9c91d-0914-483f-b9ae-8d935b448c34)

Project Structure:
![image](https://github.com/mysteryx93/HanumanInstitute.MvvmDialogs/assets/66151783/c84e0915-50ab-4f62-915a-d88dc247679a)

I use the code in ModManageViewModel, the ModManageView is a UserControl shown as a subpage in the MainWindow, and the page shows correctly so i guess it's not ViewLocator's problem. But when using the code above, and it searches for the view, it throws out errors

Also is it possible to implement the DialogOpenedEventHandler because now we only have DialogClosingEventHandler

**Comment by mysteryx93** [comment]
Could you send me a minimal reproduction project so I can take a look at it?

**Comment by mysteryx93** [comment]
The error clearly states that it can't map the ViewModel to the View; which is not done by the DI container but by the ViewLocator.

**Comment by lxymahatma** [comment]
> Could you send me a minimal reproduction project so I can take a look at it?

my project is on https://github.com/MDModsDev/MuseDashModToolsUI/tree/Dialoghost_mvvm

the new branch i created for trying to use dialog mvvm, it's not that big, the main thing i mentioned is in ModManageViewModel. but if u want to have a much smaller project to look at i can do it later cz it's 3am for me rn i have to sleep 😂

**Comment by lxymahatma** [comment]
> The error clearly states that it can't map the ViewModel to the View; which is not done by the DI container but by the ViewLocator.

yeah but what I'm really confused is it seems like avalonia itself can handle the views using my viewlocator, or i might did something wrong in DI ig(?

**Comment by mysteryx93** [comment]
Project does not start at all on Linux

**Comment by lxymahatma** [comment]
> Project does not start at all on Linux

😂 might be the problem in Program.cs?
maybe you need to comment out the #define Windows
bc im using windows and github action build for linux correctly i just forget to comment it out

**Comment by mysteryx93** [comment]
Doesn't even reach the Main method, gets stuck at initiating the debugger. Removing that define doesn't solve.

**Comment by lxymahatma** [comment]
> Doesn't even reach the Main method, gets stuck at initiating the debugger. Removing that define doesn't solve.

hmmm that's so weird, then I'll just try to make a small project to reproduce the problem ig, cz i don't have linux so i don't really know what happened 🤔
sorry for the inconvenience tho

**Comment by mysteryx93** [comment]
You can also import the MvvmDialogs source code into your project to see why it's not finding your reference, that might actually be easier

**Comment by lxymahatma** [comment]
> You can also import the MvvmDialogs source code into your project to see why it's not finding your reference, that might actually be easier

just finished with TestApp, seems like still happening to me, I hope u can run it this time 😂
[TestApp.zip](https://github.com/mysteryx93/HanumanInstitute.MvvmDialogs/files/11862441/TestApp.zip)

**Comment by lxymahatma** [comment]
> You can also import the MvvmDialogs source code into your project to see why it's not finding your reference, that might actually be easier

Seems like the problem is from here
![image](https://github.com/mysteryx93/HanumanInstitute.MvvmDialogs/assets/66151783/cb93bfc9-c168-4a72-a7a6-c54762759967)
The UserControl has the _useNavigation as false, so it goes to the else one, but it's not a Window so just threw out error

**Comment by mysteryx93** [comment]
That's called to map `ownerViewModel` to the Window that the dialog is shown into. Is `this` the ViewModel of the Window, or is it a ViewModel within a control? If that's the case, you need a reference to the parent ViewModel.

**Comment by lxymahatma** [comment]
> That's called to map `ownerViewModel` to the Window that the dialog is shown into. Is `this` the ViewModel of the Window, or is it a ViewModel within a control? If that's the case, you need a reference to the parent ViewModel.

it's a viewmodel of a UserControl, because i use dialoghost before and wrote the dialog in the UserControl's XAML, and it can open within the UserControl so I thought UserControl as parent is also fine.
That's why it's not working ig
