### ISSUE TITLE
Remove Avalonia Dependency on ReactiveUI

### ISSUE THREAD

**Issue by SeanLatimer** [mysteryx93/HanumanInstitute.MvvmDialogs#7]
I was wondering if it would be possible to remove the dependency on ReactiveUI in the Avalonia module?

I'm currently using CommunityToolkit and would rather avoid a dependency on ReactiveUI. From what I can see, the parts of ReactiveUI used here should really be left to the users implementation.

**Comment by mysteryx93** [comment]
Fair enough. I barely use it anyway. It's removed.
