### ISSUE TITLE
Sub ViewModels cannot open dialogs (WPF)

### ISSUE THREAD

**Issue by dakiller** [mysteryx93/HanumanInstitute.MvvmDialogs#8]
I have UserControls that have their own ViewModels, and I put those view models in my main window and have their VM created in the main VM and assign the UserControl's datacontext to this sub VM.

Opening a dialog in this sub VM throws the error - 'Cannot find View for viewModel of type SubViewModel'

The issue lies in MvvmDialogs.Wpf\DialogManager.cs

public override IView? FindViewByViewModel(INotifyPropertyChanged viewModel) =>
            Windows.FirstOrDefault(x => ReferenceEquals(viewModel, x.DataContext)).AsWrapper();

I do not have a window with my SubViewModel as its datacontext.

**Comment by mysteryx93** [comment]
You need to pass a reference to your host ViewModel to your UserControl, so it knows where to display.

It could be your UserControl ViewModel having a Owner property.
